<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Peer Assignment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets  
2.  Load the three datasets into three tables in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days. 

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):

- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv" target="_blank">Chicago Census Data</a>

- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv" target="_blank">Chicago Public Schools</a>

- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv" target="_blank">Chicago Crime Data</a>

**NOTE**: For the learners who are encountering issues with loading from .csv in DB2 on Firefox, you can download the .txt files and load the data with those:

- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.txt" target="_blank">Chicago Census Data</a>
    
- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.txt" target="_blank">Chicago Public Schools</a>
  
- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.txt" target="_blank">Chicago Crime Data</a>

**NOTE:** Ensure you have downloaded the datasets using the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be stored in the database.

While it is easier to read the dataset into a Pandas dataframe and then PERSIST it into the database as we saw in Week 3 Lab 3, it results in mapping to default datatypes which may not be optimal for SQL querying. For example a long textual field may map to a CLOB instead of a VARCHAR. 

Therefore, **it is highly recommended to manually load the table using the database console LOAD tool, as indicated in Week 2 Lab 1 Part II**. The only difference with that lab is that in Step 5 of the instructions you will need to click on create "(+) New Table" and specify the name of the table you want to create and then click "Next". 

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/LoadingData.png">

##### Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the first dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new tables as follows:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

The following required modules are pre-installed in the Skills Network Labs environment. However if you run this notebook commands in a different Jupyter environment (e.g. Watson Studio or Ananconda) you may need to install these libraries by removing the `#` sign before `!pip` in the code cell below.

In [ ]:
# These libraries are pre-installed in SN Labs. If running in another environment please uncomment lines below to install them:
# !pip install --force-reinstall ibm_db==3.1.0 ibm_db_sa==0.3.3
# Ensure we don't load_ext with sqlalchemy>=1.4 (incompadible)
# !pip uninstall sqlalchemy==1.4 -y && pip install sqlalchemy==1.3.24
# !pip install ipython-sql

In [1]:
%load_ext sql

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance in first lab in Week 3. From your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/details.png">

In [3]:
# Remember the connection string is of the format:
# %sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL
# Enter the connection string for your Db2 on Cloud database instance below
%sql ibm_db_sa://chn72616:HBv9C0rej4TY5NF2@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb?security=SSL

'Connected: chn72616@bludb'

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [4]:
%%sql
Select Count(*) as Total_Number_of_Crimes from CHICAGO_CRIME_DATA

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[(533,)]

### Problem 2

##### List community areas with per capita income less than 11000.

In [5]:
%%sql
Select COMMUNITY_AREA_NAME FROM CENSUS_DATA WHERE PER_CAPITA_INCOME < 11000

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[('West Garfield Park',),
 ('South Lawndale',),
 ('Fuller Park',),
 ('Riverdale',)]

### Problem 3

##### List all case numbers for crimes  involving minors?(children are not considered minors for the purposes of crime analysis)

In [6]:
%%sql
Select * from CHICAGO_CRIME_DATA WHERE DOMESTIC = TRUE;

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[(8863261, 'HV537004', datetime.date(2012, 10, 25), '054XX N ASHLAND AVE', '810', 'THEFT', 'OVER $500', 'OTHER', 'FALSE', 'TRUE', 2012, 20, 40, 77, '6', 1164674, 1936421, 2012, Decimal('41.98115315'), Decimal('-87.66975020'), '(41.981153152, -87.669750197)'),
 (9682442, 'HX332979', datetime.date(2014, 7, 5), '042XX W 55TH ST', '820', 'THEFT', '$500 AND UNDER', 'APARTMENT', 'FALSE', 'TRUE', 813, 8, 13, 62, '6', 1148818, 1867790, 2014, Decimal('41.79314445'), Decimal('-87.72983895'), '(41.793144448, -87.729838952)'),
 (1778867, 'G597730', datetime.date(2001, 10, 5), '024XX W HADDON AV', '460', 'BATTERY', 'SIMPLE', 'STREET', 'FALSE', 'TRUE', 1312, 12, None, None, '08B', 1159562, 1907600, 2001, Decimal('41.90217367'), Decimal('-87.68934680'), '(41.902173665, -87.689346803)'),
 (1887291, 'G736811', datetime.date(2001, 12, 9), '035XX W DICKENS AV', '460', 'BATTERY', 'SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 1413, 14, None, None, '08B', 1152633, 1913771, 2001, Decimal('41.91924736'), Decimal('-87.71463465'), '(41.919247363, -87.714634645)'),
 (8418606, 'HT651635', datetime.date(2011, 12, 29), '056XX W ROOSEVELT RD', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'PARKING LOT/GARAGE(NON.RESID.)', 'FALSE', 'TRUE', 1513, 15, 29, 25, '08B', 1139135, 1894124, 2011, Decimal('41.86559007'), Decimal('-87.76470700'), '(41.865590065, -87.764706995)'),
 (1719296, 'G517474', datetime.date(2001, 8, 29), '017XX W 59 ST', '460', 'BATTERY', 'SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 714, 7, None, None, '08B', 1165757, 1865528, 2001, Decimal('41.78659414'), Decimal('-87.66778928'), '(41.786594143, -87.66778928)'),
 (1353618, 'G056330', datetime.date(2001, 1, 27), '078XX S SAWYER AV', '460', 'BATTERY', 'SIMPLE', 'RESIDENCE PORCH/HALLWAY', 'TRUE', 'TRUE', 835, 8, None, None, '08B', 1156032, 1852572, 2001, Decimal('41.75124194'), Decimal('-87.70379416'), '(41.751241937, -87.703794164)'),
 (5979106, 'HN772519', datetime.date(2007, 12, 22), '081XX S GREEN ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 613, 6, 21, 71, '08B', 1172054, 1850881, 2007, Decimal('41.74626491'), Decimal('-87.64513091'), '(41.746264912, -87.645130909)'),
 (10179921, 'HY368284', datetime.date(2015, 8, 4), '024XX S TROY ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'TRUE', 'TRUE', 1033, 10, 12, 30, '08B', 1155747, 1887668, 2015, Decimal('41.84755595'), Decimal('-87.70389680'), '(41.847555951, -87.703896798)'),
 (8142216, 'HT375934', datetime.date(2011, 7, 1), '058XX S SANGAMON ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 712, 7, 16, 68, '08B', 1170970, 1866261, 2011, Decimal('41.78849326'), Decimal('-87.64865431'), '(41.788493256, -87.648654314)'),
 (11133668, 'JA490957', datetime.date(2017, 10, 29), '107XX S LAFAYETTE AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENTIAL YARD (FRONT/BACK)', 'FALSE', 'TRUE', 513, 5, 34, 49, '08B', 1177830, 1833729, 2017, Decimal('41.69906886'), Decimal('-87.62448396'), '(41.699068864, -87.624483962)'),
 (2281487, 'HH558381', datetime.date(2002, 8, 4), '051XX W MADISON ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 1533, 15, 28, 25, '08B', 1142023, 1899535, 2002, Decimal('41.88038556'), Decimal('-87.75397078'), '(41.880385563, -87.753970777)'),
 (9806771, 'HX455839', datetime.date(2014, 10, 5), '096XX S WOODLAWN AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 511, 5, 8, 50, '08B', 1185895, 1841338, 2014, Decimal('41.71976292'), Decimal('-87.59471496'), '(41.719762924, -87.594714959)'),
 (4328714, 'HL632721', datetime.date(2005, 9, 23), '020XX W 18TH ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 1223, 12, 25, 31, '08B', 1163120, 1891403, 2005, Decimal('41.85765368'), Decimal('-87.67673292'), '(41.85765368, -87.676732923)'),
 (6514506, 'HP579910', datetime.date(2008, 9, 18), '067XX S EBERHART AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'STREET', 'FALSE', 'TRUE', 321, 3, 20, 42, '08B', 1180737, 1860533, 2008, Decimal('41.77255605'), Decimal('-87.61301853'), '(41.772556054, -87.613018533)'),
 (4424181, 'HL718742', datetime.date(2005, 11, 6), '007XX N LAWNDALE AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE PORCH/HALLWAY', 'FALSE', 'TRUE', 1112, 11, 27, 23, '08B', 1151588, 1904632, 2005, Decimal('41.89418971'), Decimal('-87.71871472'), '(41.894189705, -87.718714722)'),
 (6644648, 'HP714065', datetime.date(2008, 12, 3), '014XX N MENARD AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 2531, 25, 29, 25, '08B', 1137418, 1908965, 2008, Decimal('41.90634674'), Decimal('-87.77065305'), '(41.906346741, -87.770653047)'),
 (9337353, 'HW481295', datetime.date(2013, 10, 5), '016XX S ST LOUIS AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'TRUE', 'TRUE', 1021, 10, 24, 29, '08B', 1153305, 1891618, 2013, Decimal('41.85844398'), Decimal('-87.71275427'), '(41.858443981, -87.712754265)'),
 (11277173, 'JB213238', datetime.date(2018, 4, 6), '022XX N PARKSIDE AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 2515, 25, 37, 19, '08B', 1138350, 1914356, 2018, Decimal('41.92112344'), Decimal('-87.76709866'), '(41.92112344, -87.767098657)'),
 (7002482, 'HR408597', datetime.date(2009, 7, 3), '030XX W JACKSON BLVD', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 1124, 11, 28, 27, '08B', 1156002, 1898529, 2009, Decimal('41.87735457'), Decimal('-87.70266813'), '(41.877354573, -87.702668131)'),
 (8315579, 'HT542713', datetime.date(2011, 10, 14), '034XX N PAULINA ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESTAURANT', 'FALSE', 'TRUE', 1924, 19, 32, 6, '08B', 1164380, 1922814, 2011, Decimal('41.94382121'), Decimal('-87.67121812'), '(41.94382121, -87.671218121)'),
 (7692081, 'HS498285', datetime.date(2010, 9, 4), '006XX W MELROSE ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 2332, 19, 44, 6, '08B', 1171428, 1921885, 2010, Decimal('41.94111969'), Decimal('-87.64534052'), '(41.941119685, -87.645340518)'),
 (2584554, 'HH867007', datetime.date(2002, 12, 30), '040XX W IRVING PARK RD', '499', 'BATTERY', 'AGGRAVATED DOMESTIC BATTERY', 'RESIDENCE', 'TRUE', 'TRUE', 1732, 17, 39, 16, '04B', 1148845, 1926278, 2002, Decimal('41.95364179'), Decimal('-87.72822799'), '(41.953641789, -87.728227991)'),
 (3020236, 'HJ724585', datetime.date(2003, 10, 29), '015XX S HAMLIN AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 1014, 10, 24, 29, '08B', 1151293, 1892263, 2003, Decimal('41.86025361'), Decimal('-87.72012274'), '(41.860253606, -87.720122737)'),
 (1465880, 'G198370', datetime.date(2001, 4, 7), '0000X N PINE AV', '430', 'BATTERY', 'AGGRAVATED: OTHER DANG WEAPON', 'RESIDENCE', 'FALSE', 'TRUE', 1522, 15, None, None, '04B', 1139534, 1900041, 2001, Decimal('41.88181984'), Decimal('-87.76309792'), '(41.881819836, -87.763097916)'),
 (3017838, 'HJ723825', datetime.date(2003, 10, 28), '044XX S DREXEL BLVD', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 2123, 2, 4, 39, '08B', 1182938, 1875792, 2003, Decimal('41.81437718'), Decimal('-87.60447613'), '(41.814377178, -87.604476134)'),
 (2804858, 'HJ458342', datetime.date(2003, 6, 28), '015XX N WELLS ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 1821, 18, 43, 8, '08B', 1174421, 1910623, 2003, Decimal('41.91014987'), Decimal('-87.63467747'), '(41.910149869, -87.634677466)'),
 (6481371, 'HP558812', datetime.date(2008, 9, 7), '041XX W 57TH ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 813, 8, 13, 62, '08B', 1149766, 1866484, 2008, Decimal('41.78954227'), Decimal('-87.72639650'), '(41.789542268, -87.726396498)'),
 (5663639, 'HN472326', datetime.date(2007, 7, 17), '010XX N KEYSTONE AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 1111, 11, 37, 23, '08B', 1149197, 1906636, 2007, Decimal('41.89973555'), Decimal('-87.72744421'), '(41.899735553, -87.727444212)'),
 (3663835, 'HK756778', datetime.date(2004, 11, 17), '054XX S LAFLIN ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 932, 9, 16, 61, '08B', 1167261, 1868636, 2004, Decimal('41.79509079'), Decimal('-87.66218586'), '(41.795090788, -87.662185864)'),
 (2423472, 'HH741961', datetime.date(2002, 10, 27), '010XX N WALLER AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'STREET', 'FALSE', 'TRUE', 1511, 15, 29, 25, '08B', 1138162, 1906418, 2002, Decimal('41.89934404'), Decimal('-87.76798167'), '(41.89934404, -87.767981666)'),
 (9035595, 'HW182288', datetime.date(2013, 3, 6), '046XX S LANGLEY AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 221, 2, 4, 38, '08B', 1181712, 1874461, 2013, Decimal('41.81075326'), Decimal('-87.60901434'), '(41.810753256, -87.609014335)'),
 (10549382, 'HZ295843', datetime.date(2016, 6, 6), '015XX S HOMAN AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'STREET', 'FALSE', 'TRUE', 1021, 10, 24, 29, '08B', 1153951, 1892227, 2016, Decimal('41.86010231'), Decimal('-87.71036680'), '(41.860102309, -87.710366798)'),
 (5080475, 'HM673431', datetime.date(2006, 10, 21), '094XX S WENTWORTH AVE', '420', 'BATTERY', 'AGGRAVATED:KNIFE/CUTTING INSTR', 'RESIDENCE', 'FALSE', 'TRUE', 634, 6, 21, 49, '04B', 1176612, 1842280, 2006, Decimal('41.72256142'), Decimal('-87.62868748'), '(41.72256142, -87.628687477)'),
 (6939024, 'HR286405', datetime.date(2009, 4, 25), '052XX W CONGRESS PKWY', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'FALSE', 'TRUE', 1522, 15, 29, 25, '08B', 1141598, 1897182, 2009, Decimal('41.87393649'), Decimal('-87.75558951'), '(41.873936494, -87.755589514)'),
 (9116765, 'HW261668', datetime.date(2013, 5, 5), '003XX N PULASKI RD', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 1114, 11, 28, 26, '08B', 1149673, 1901704, 2013, Decimal('41.88619239'), Decimal('-87.72582411'), '(41.886192389, -87.725824111)'),
 (11137994, 'JA496716', datetime.date(2017, 11, 2), '008XX N WASHTENAW AVE', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', 'TRUE', 'TRUE', 1211, 12, 26, 24, '08B', 1158244, 1905393, 2017, Decimal('41.89614452'), Decimal('-87.69424841'), '(41.896144516, -87.694248407)'),
 (11014534, 'JA344492', datetime.date(2017, 7, 12), '009XX E 132ND PL', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'APARTMENT', 'TRUE', 'TRUE', 533, 5, 9, 54, '08B', 1185380, 1817834, 2017, Decimal('41.65527698'), Decimal('-87.59733674'), '(41.655276978, -87.597336736)'),
 (6806337, 'HR217367', datetime.date(2009, 3, 15), '051XX W KINZIE ST', '486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 1532, 15, 28, 25, '08B', 1142136, 1902250, 2009, Decimal('41.88783376'), Decimal('-87.75348849'), '(41.887833763, -87.753488486)'),
 (7468176, 'HS269736', datetime.date(2010, 4, 22), '051XX S INGLESIDE AVE', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'STREET', 'FALSE', 'TRUE', 2124, 2, 4, 41, '14', 1183412, 1871257, 2010, Decimal('41.80192174'), Decimal('-87.60287886'), '(41.801921744, -87.602878856)'),
 (2048711, 'HH262924', datetime.date(2002, 3, 24), '055XX W HARRISON ST', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'SIDEWALK', 'FALSE', 'TRUE', 1522, 15, None, None, '14', 1139534, 1896770, 2002, Decimal('41.87284378'), Decimal('-87.76317771'), '(41.872843784, -87.763177706)'),
 (10079280, 'HY267896', datetime.date(2015, 5, 20), '115XX S STEWART AVE', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'RESIDENTIAL YARD (FRONT/BACK)', 'FALSE', 'TRUE', 522, 5, 34, 53, '14', 1175695, 1828405, 2015, Decimal('41.68450696'), Decimal('-87.63245993'), '(41.684506962, -87.632459932)'),
 (5758092, 'HN568531', datetime.date(2007, 9, 4), '052XX S CARPENTER ST', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'RESIDENCE', 'FALSE', 'TRUE', 934, 9, 16, 61, '14', 1170202, 1870108, 2007, Decimal('41.79906661'), Decimal('-87.65135838'), '(41.799066605, -87.651358383)'),
 (9817983, 'HX467661', datetime.date(2014, 10, 14), '013XX S HOMAN AVE', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'STREET', 'TRUE', 'TRUE', 1021, 10, 24, 29, '14', 1153916, 1893520, 2014, Decimal('41.86365114'), Decimal('-87.71046084'), '(41.863651143, -87.71046084)'),
 (4728934, 'HM337445', datetime.date(2006, 5, 7), '028XX N LARAMIE AVE', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'STREET', 'FALSE', 'TRUE', 2514, 25, 31, 19, '14', 1141225, 1918275, 2006, Decimal('41.93182501'), Decimal('-87.75643821'), '(41.931825006, -87.756438211)'),
 (9305467, 'HW449676', datetime.date(2013, 9, 13), '039XX W GLADYS AVE', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'APARTMENT', 'FALSE', 'TRUE', 1132, 11, 24, 26, '14', 1150166, 1898065, 2013, Decimal('41.87619698'), Decimal('-87.72410855'), '(41.876196982, -87.724108549)'),
 (7781193, 'HS589302', datetime.date(2010, 10, 29), '095XX S CONSTANCE AVE', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'RESIDENCE', 'FALSE', 'TRUE', 431, 4, 7, 51, '14', 1190183, 1842108, 2010, Decimal('41.72177386'), Decimal('-87.57898476'), '(41.721773858, -87.578984755)'),
 (6007606, 'HN784049', datetime.date(2007, 12, 29), '026XX W 84TH PL', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'RESIDENCE', 'FALSE', 'TRUE', 835, 8, 18, 70, '14', 1160125, 1848565, 2007, Decimal('41.74016294'), Decimal('-87.68890519'), '(41.740162942, -87.688905189)'),
 (10218934, 'HY405637', datetime.date(2015, 9, 1), '057XX S CAMPBELL AVE', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'APARTMENT', 'FALSE', 'TRUE', 824, 8, 16, 63, '14', 1160682, 1866595, 2015, Decimal('41.78962843'), Decimal('-87.68636753'), '(41.789628428, -87.686367529)'),
 (8300838, 'HT535175', datetime.date(2011, 10, 8), '037XX W WILSON AVE', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'APARTMENT', 'FALSE', 'TRUE', 1723, 17, 39, 14, '26', 1150552, 1930307, 2011, Decimal('41.96466441'), Decimal('-87.72184715'), '(41.964664408, -87.721847151)'),
 (10811959, 'JA110097', datetime.date(2017, 1, 10), '019XX N HAMLIN AVE', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'RESIDENCE', 'FALSE', 'TRUE', 2535, 25, 26, 22, '26', 1150735, 1912671, 2017, Decimal('41.91626623'), Decimal('-87.72163701'), '(41.916266226, -87.721637009)'),
 (4750131, 'HM360756', datetime.date(2006, 5, 19), '071XX N PAULINA ST', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'RESIDENCE', 'FALSE', 'TRUE', 2423, 24, 49, 1, '26', 1163884, 1947582, 2006, Decimal('42.01179600'), Decimal('-87.67233871'), '(42.011795997, -87.67233871)'),
 (10779118, 'HZ544441', datetime.date(2016, 12, 8), '010XX W 51ST ST', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'APARTMENT', 'FALSE', 'TRUE', 933, 9, 16, 61, '26', 1170415, 1871001, 2016, Decimal('41.80151246'), Decimal('-87.65055125'), '(41.801512455, -87.650551251)'),
 (4374455, 'HL660560', datetime.date(2005, 10, 8), '058XX S KEELER AVE', '4387', 'OTHER OFFENSE', 'VIOLATE ORDER OF PROTECTION', 'RESIDENCE', 'TRUE', 'TRUE', 813, 8, 13, 62, '26', 1149366, 1865564, 2005, Decimal('41.78702538'), Decimal('-87.72788695'), '(41.787025384, -87.727886949)'),
 (6993831, 'HR399710', datetime.date(2009, 6, 23), '017XX W 18TH ST', '2825', 'OTHER OFFENSE', 'HARASSMENT BY TELEPHONE', 'RESIDENCE', 'FALSE', 'TRUE', 1223, 12, 25, 31, '26', 1164905, 1891447, 2009, Decimal('41.85773678'), Decimal('-87.67017968'), '(41.857736775, -87.670179675)'),
 (6054992, 'HP157774', datetime.date(2008, 2, 3), '047XX W BELDEN AVE', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'APARTMENT', 'FALSE', 'TRUE', 2522, 25, 31, 19, '26', 1144244, 1914869, 2008, Decimal('41.92242233'), Decimal('-87.74542953'), '(41.922422328, -87.745429533)'),
 (6252456, 'HP340132', datetime.date(2008, 5, 16), '048XX S LAKE PARK AVE', '2826', 'OTHER OFFENSE', 'HARASSMENT BY ELECTRONIC MEANS', 'APARTMENT', 'FALSE', 'TRUE', 2132, 2, 4, 39, '26', None, None, 2008, None, None, None),
 (5601454, 'HN407116', datetime.date(2007, 6, 15), '047XX W IRVING PARK RD', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'OTHER', 'FALSE', 'TRUE', 1722, 17, 45, 15, '26', 1143937, 1926169, 2007, Decimal('41.95343636'), Decimal('-87.74627323'), '(41.953436358, -87.746273229)'),
 (10197369, 'HY385205', datetime.date(2015, 8, 16), '013XX W 56TH ST', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'APARTMENT', 'FALSE', 'TRUE', 713, 7, 16, 67, '26', 1168181, 1867622, 2015, Decimal('41.79228849'), Decimal('-87.65884139'), '(41.792288494, -87.658841391)'),
 (3646946, 'HK743113', datetime.date(2004, 11, 10), '080XX S MARYLAND AVE', '2825', 'OTHER OFFENSE', 'HARASSMENT BY TELEPHONE', 'APARTMENT', 'FALSE', 'TRUE', 631, 6, 8, 44, '26', 1183297, 1851935, 2004, Decimal('41.74890306'), Decimal('-87.60390164'), '(41.74890306, -87.603901641)'),
 (6769056, 'HR185873', datetime.date(2009, 2, 24), '069XX S WOODLAWN AVE', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'RESIDENCE', 'FALSE', 'TRUE', 321, 3, 5, 69, '26', 1185601, 1859225, 2009, Decimal('41.76885361'), Decimal('-87.59522983'), '(41.76885361, -87.595229828)'),
 (7255767, 'HR668156', datetime.date(2009, 11, 30), '006XX W 61ST ST', '4387', 'OTHER OFFENSE', 'VIOLATE ORDER OF PROTECTION', 'RESIDENCE', 'TRUE', 'TRUE', 711, 7, 20, 68, '26', 1173080, 1864440, 2009, Decimal('41.78344986'), Decimal('-87.64097151'), '(41.783449861, -87.640971514)'),
 (9426342, 'HW569852', datetime.date(2013, 12, 11), '0000X N WALLER AVE', '5002', 'OTHER OFFENSE', 'OTHER VEHICLE OFFENSE', 'RESIDENCE', 'TRUE', 'TRUE', 1513, 15, 29, 25, '26', 1138158, 1899781, 2013, Decimal('41.88113134'), Decimal('-87.76815693'), '(41.88113134, -87.768156926)'),
 (5322667, 'HN182437', datetime.date(2007, 2, 17), '091XX S COTTAGE GROVE AVE', '560', 'ASSAULT', 'SIMPLE', 'SIDEWALK', 'FALSE', 'TRUE', 633, 6, 8, 44, '08A', 1183165, 1844391, 2007, Decimal('41.72820456'), Decimal('-87.60461941'), '(41.728204555, -87.604619408)'),
 (9271865, 'HW415978', datetime.date(2013, 8, 20), '050XX W JACKSON BLVD', '051A', 'ASSAULT', 'AGGRAVATED: HANDGUN', 'SIDEWALK', 'FALSE', 'TRUE', 1533, 15, 28, 25, '04A', 1143027, 1898205, 2013, Decimal('41.87671722'), Decimal('-87.75031732'), '(41.87671722, -87.750317319)'),
 (10502099, 'HZ242203', datetime.date(2016, 4, 27), '028XX W ARTHINGTON ST', '520', 'ASSAULT', 'AGGRAVATED:KNIFE/CUTTING INSTR', 'APARTMENT', 'FALSE', 'TRUE', 1135, 11, 2, 27, '04A', 1157555, 1895912, 2016, Decimal('41.87014181'), Decimal('-87.69703716'), '(41.87014181, -87.697037158)'),
 (10950230, 'JA269772', datetime.date(2017, 5, 18), '038XX W MONROE ST', '051A', 'ASSAULT', 'AGGRAVATED: HANDGUN', 'STREET', 'TRUE', 'TRUE', 1122, 11, 28, 26, '04A', 1150782, 1899386, 2017, Decimal('41.87980993'), Decimal('-87.72181223'), '(41.879809931, -87.721812233)'),
 (4892475, 'HM507529', datetime.date(2006, 7, 28), '074XX S MORGAN ST', '560', 'ASSAULT', 'SIMPLE', 'RESIDENCE', 'FALSE', 'TRUE', 733, 7, 17, 68, '08A', 1170929, 1855598, 2006, Decimal('41.75923359'), Decimal('-87.64911570'), '(41.759233594, -87.649115701)'),
 (10653179, 'HZ403432', datetime.date(2016, 8, 23), '008XX E 65TH ST', '051A', 'ASSAULT', 'AGGRAVATED: HANDGUN', 'APARTMENT', 'TRUE', 'TRUE', 312, 3, 20, 42, '04A', 1183153, 1862099, 2016, Decimal('41.77679744'), Decimal('-87.60411357'), '(41.776797435, -87.604113569)'),
 (8789058, 'HV462975', datetime.date(2012, 9, 5), '057XX S ROCKWELL ST', '560', 'ASSAULT', 'SIMPLE', 'STREET', 'FALSE', 'TRUE', 824, 8, 16, 63, '08A', 1160020, 1866486, 2012, Decimal('41.78934296'), Decimal('-87.68879789'), '(41.789342962, -87.688797892)'),
 (1962624, 'HH154448', datetime.date(2002, 1, 28), '064XX S PEORIA DR', '560', 'ASSAULT', 'SIMPLE', 'RESIDENCE', 'TRUE', 'TRUE', 723, 7, None, None, '08A', 1171787, 1862205, 2002, Decimal('41.77734524'), Decimal('-87.64577760'), '(41.777345235, -87.645777602)'),
 (11111810, 'JA462321', datetime.date(2017, 10, 7), '064XX S MORGAN ST', '520', 'ASSAULT', 'AGGRAVATED:KNIFE/CUTTING INSTR', 'APARTMENT', 'TRUE', 'TRUE', 724, 7, 16, 68, '04A', 1170753, 1862070, 2017, Decimal('41.77699740'), Decimal('-87.64957217'), '(41.776997403, -87.649572168)'),

### Problem 4

##### List all kidnapping crimes involving a child?

In [8]:
%%sql
SELECT PRIMARY_TYPE,DOMESTIC FROM CHICAGO_CRIME_DATA WHERE PRIMARY_TYPE = KIDNAPPING;

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "KIDNAPPING" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206
[SQL: SELECT PRIMARY_TYPE,DOMESTIC FROM CHICAGO_CRIME_DATA WHERE PRIMARY_TYPE = KIDNAPPING;]
(Background on this error at: http://sqlalche.me/e/13/f405)

### Problem 5

##### What kinds of crimes were recorded at schools?

In [13]:
%%sql
SELECT PRIMARY_TYPE FROM CHICAGO_CRIME_DATA WHERE LOCATION_DESCRIPTION =' SCHOOL';

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[]

### Problem 6

##### List the average safety score for each type of school.

In [18]:
%%sql
SELECT AVG(SAFETY_SCORE) AS AVERAGE_SAFETY_SCHOOL FROM CHICAGO_PUBLIC_SCHOOL;

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[(49,)]

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [19]:
%%sql
select COMMUNITY_AREA_NAME 
from CENSUS_DATA
order by PERCENT_HOUSEHOLDs_BELOW_POVERTY desc  
limit 5

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[('Riverdale',),
 ('Fuller Park',),
 ('Englewood',),
 ('North Lawndale',),
 ('East Garfield Park',)]

### Problem 8

##### Which community area is most crime prone?

In [20]:
%%sql
SELECT COMMUNITY_AREA_NUMBER, COUNT(*) as crime_count
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY crime_count DESC
LIMIT 1;

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[(25, 43)]

Double-click **here** for a hint

<!--
Query for the 'community area number' that is most crime prone.
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [21]:
%%sql
SELECT COMMUNITY_AREA_NAME, HARDSHIP_INDEX
FROM CENSUS_DATA
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM census_data);

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[('Riverdale', 98)]

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [25]:
%%sql
SELECT COMMUNITY_AREA_NUMBER, COUNT(*) as crime_count
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY crime_count DESC
LIMIT 1;

 * ibm_db_sa://chn72616:***@824dfd4d-99de-440d-9991-629c01b3832d.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:30119/bludb
Done.

[(25, 43)]

Copyright © 2020 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork22-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>

## Change log

| Date       | Version | Changed by    | Change Description                 |
| ---------- | ------- | ------------- | ---------------------------------- |
| 2021-11-17  | 2.6  | Lakshmi  | Updated library  |
| 2021-05-19 | 2.4     | Lakshmi Holla | Updated the question   |
| 2021-04-30 | 2.3     | Malika Singla | Updated the libraries   |
| 2021-01-15 | 2.2     | Rav Ahuja | Removed problem 11 and fixed changelog |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets |
| 2020-09-05 | 2.0     | Malika Singla | Moved lab to course repo in GitLab |
| 2018-07-18 | 1.0     | Rav Ahuja | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan | Created initial version |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>